language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "7.9"
  
before_script:
  - npm install

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: false

install: true

services:
  - mongodb
  
script:
  - npm test
